### PR TITLE
Added a sidebar for navigation

### PR DESCRIPTION
**Pull request by vaibhav-009**
I have added a sidebar for navigation on the page

### PR Title
The purpose of this Pull Request is to fix #91 

### Description
This will display all the content heading in a sidebar. It will easy to navigate the website.

### Screenshot
image

### CODE REVIEW

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
Good work with it, but the Ui doesn't go well, can you plz change it

**Comment by vaibhav-009** [comment]
image
is this okay ?

**Comment by EshanTrivedi21** [comment]
is it possible to shift the main content to the right a bit such that 25% from left is the navbar and rest 75% is the main content..
also is the navbar scrollable as well? @vaibhav-009

**Comment by vaibhav-009** [comment]
image
like this ? 
And the navbar is scrollable.

**Comment by EshanTrivedi21** [comment]
also what about this in the mobile? can you add a hamburger navbar

**Comment by vaibhav-009** [comment]
Yes I can add it but I will appreciate if you can merge this PR and raises a separate issue for hamburger navbar.

**Review by EshanTrivedi21 — APPROVED** [review]
Great work! You can go on with the hamburger work 🚀

**Pull request merged**
