### PR TITLE
updated download button

### PR DESCRIPTION
**Pull request by SugamKuber**
image
looks better and clear

### CODE REVIEW

**Review by EshanTrivedi21 — COMMENTED** [review]
Na bhai the location of the previous one looked better

**Comment by SugamKuber** [comment]
The location is the same actually, i just changed the style of button

**Comment by SugamKuber** [comment]
Now every button in website is similar, buttons are unifrom

**Comment by EshanTrivedi21** [comment]
Can you plz remove the top and the bottom button.. that's a big turnoff @SugamKuber

**Comment by SugamKuber** [comment]
image
I have removed it

**Review by EshanTrivedi21 — APPROVED** [review]

**Pull request merged**
