### PR TITLE
Store Credential in Disk 

### PR DESCRIPTION
**Pull request by devjj248**
New Command added for storing credential in disk

### CODE REVIEW

**Comment by devjj248** [comment]
@EshanTrivedi21 Check this one also

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
Heyy.. it's greatt!! Can you plz add the changes you made in the website as well and in a single repo..
Thanks!

**Comment by devjj248** [comment]
@EshanTrivedi21 Its Done For Both Ones

**Review by EshanTrivedi21 — APPROVED** [review]

**Comment by devjj248** [comment]
@EshanTrivedi21 There?

**Comment by devjj248** [comment]
Can You add `hacktoberfest-accepted` label

**Review by EshanTrivedi21 — COMMENTED** [review]
Good one 👍

**Pull request merged**
