### PR TITLE
added light/dark mode toggle button to your website

### PR DESCRIPTION
**Pull request by shrutilenka**
Hope you are satisfied with the improvements I added to your website. Do let me know if anything you want to modify.

### CODE REVIEW

**Comment by shrutilenka** [comment]
@EshanTrivedi21

**Review by EshanTrivedi21 — APPROVED** [review]

**Review by EshanTrivedi21 — APPROVED** [review]

**Comment by EshanTrivedi21** [comment]
Great work @shrutilenka!!
Much appreciated! Thanks for your involvement!
Hope to work with you again..

**Comment by shrutilenka** [comment]
> Great work @shrutilenka!! Much appreciated! Thanks for your involvement! Hope to work with you again..

Thanks a lot sir.It would be my pleasure to work with you again. For future work collaboration, you can reach me at shrutilenka1202@gmail.com

**Comment by EshanTrivedi21** [comment]
> > Great work @shrutilenka!! Much appreciated! Thanks for your involvement! Hope to work with you again..
> 
> Thanks a lot sir.It would be my pleasure to work with you again. For future work collaboration, you can reach me at shrutilenka1202@gmail.com

Sure Sure would be amazing to work with you :) @shrutilenka

**Pull request merged**
