### PR TITLE
Share buttons added

### PR DESCRIPTION
**Pull request by jsvigneshkanna**
Description:

Share buttons added both for mobile and desktop view

Issue: #59 

Screenshot:
image

image

### CODE REVIEW

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
Great Work Brother, but can you please add it on the end of the Container @jsvigneshkanna

**Comment by jsvigneshkanna** [comment]
@EshanTrivedi21 at footer?

**Comment by jsvigneshkanna** [comment]
@EshanTrivedi21 ,
position updated

image

**Review by EshanTrivedi21 — APPROVED** [review]
Great work brother, go on 🚀🚀

**Pull request merged**
