### PR TITLE
fix styling of the search bar

### PR DESCRIPTION
**Pull request by Abhay5855**
Added a search icon in the search bar and responsiveness in different devices.

### CODE REVIEW

**Comment by Abhay5855** [comment]
Hey @EshanTrivedi21  I have made the search bar at the top so that users don't have to search down and added some styling to the search bar can you review it and merge it finally it has no conflicts with the main
image

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Search bar at the top - this pull request has no merge conflicts you can check 
https://github.com/EshanTrivedi21/Git-CheatSheet/pull/96

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
@Abhay5855 Great work with the Search Button UI, but there is one issue, because the label is above, easy navigation is not possible, can you please place it just above the topics section

**Comment by Abhay5855** [comment]
@EshanTrivedi21  Sure I will just make the changes, Thanks

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Hey Done with the changes moved the Search bar at the top of the topics section.
image

**Review by EshanTrivedi21 — APPROVED** [review]
Kudos to you @Abhay5855

**Comment by Abhay5855** [comment]
@EshanTrivedi21 Thanks for accepting my PR , in my Hactoberfest profile it is showing not accepted can you look into it

**Comment by EshanTrivedi21** [comment]
It will show up in the waiting list for 7 days after which it would be updated and accepted.. its a hacktoberfest policy to surpass a 7 day waiting period @Abhay5855

**Pull request merged**
