### PR TITLE
adding scroll to top feature

### LINKED ISSUE #87: Creating a Scroll to top button
**Is your feature request related to a problem? Please describe.**
Easy Navigation is missing

**Describe the solution you'd like**
The button should fade in when any scrolling takes place such that when clicked on the button we should be navigated to the top of the website

**Describe alternatives you've considered**
A similar search button which navigated you to the search bar

**Additional context**
image

### PR DESCRIPTION
**Pull request by Gopal2021025**
# FIXES #87 
Scroll bar to top has been added
scroll top

### CODE REVIEW

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
Great work @Gopal2021025, but can you plase cange the theme of the button to neumorphism and then update the pr?
image
Like this one

**Comment by EshanTrivedi21** [comment]
@Gopal2021025, what's the progress??

**Comment by Gopal2021025** [comment]
@EshanTrivedi21 I will update it

**Comment by Gopal2021025** [comment]
@EshanTrivedi21 I have made the required changes Kindly check

**Comment by EshanTrivedi21** [comment]
Can you please attach a screenshot? @Gopal2021025

**Comment by Gopal2021025** [comment]
@EshanTrivedi21 Kindly check I have attached the screenshots

**Pull request merged**
