### PR TITLE
Modify Cheatsheet 

### PR DESCRIPTION
**Pull request by ibrahim-ogunbiyi**
I'd modify the cheatsheet please kindly review it. Thanks

### CODE REVIEW

**Review by EshanTrivedi21 — COMMENTED** [review]
Can I please get the Test Image of the PDF, so that I can approve it?

**Comment by ibrahim-ogunbiyi** [comment]
image

This is it. Thanks

**Comment by ibrahim-ogunbiyi** [comment]
Wow, thank you so much. Lol, this is my first PR in live.

**Comment by EshanTrivedi21** [comment]
Great work buddy! Go on!!
You can also contribute more, towards any issue you feel like, while using it!
Let me know about the problem, and I will create an issue and assign it to you.. or you yourself can create an issue!
Go on brother!!
@ibrahim-ogunbiyi

**Pull request merged**
