### PR TITLE
Added a vertical Navbar to the left side

### PR DESCRIPTION
**Pull request by Aishaa-26**

### CODE REVIEW

**Comment by Aishaa-26** [comment]
@EshanTrivedi21 Please merge my pull-request.

**Comment by subhans11** [comment]
Hey @Aishaa-26 nice work, 
but the sidebar menu and Main content is **overlapping**.

Screenshot (164)

Suggesting you to reduce the width from 250px to 200px for #cssmenu and #cssmenu > ul

200px

and you can also work on changing it for the dark mode.

**Comment by Aishaa-26** [comment]
Sure will solve this....Thanks for the input.

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
There are a lot of issues @Aishaa-26 
1. Topics aren't fitting on the screen, there are missing topics which are hidden 
image
2. The navbar theme is not matching with the Website's theme
3. The navbar is not responsive to the light-dark mode
4. This thing is not cleaned
image
I'm closing these issues, please make the changes and request on single Pull Request.. Thanks for the efforts though, Good Work
Also thanks @subhans11

**Pull request closed without merging**
