### PR TITLE
Enhancing Page by adding "Find yourself in Github" section

### PR DESCRIPTION
**Pull request by pooranjoyb**
### Description

With this enhancement, the user will be able to search him/her in Github after looking at the Git-Cheatsheet, eventually giving a better user experience in the page.

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've added the section in the Navbar for easy Navigation
- [x] I ensured that the page remains responsive after the addition of the custom CSS

## Add relevant screenshot or video (if any)

screenshot

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Please review the deployment in my fork and let me know if changes are necessary :) @EshanTrivedi21

**Review by EshanTrivedi21 — APPROVED** [review]
Excellent Work! The design appears to be a little off, but the functioning is perfect; I'll do the design modifications once I'm a little more free. Thank you so much for your contribution.

**Comment by pooranjoyb** [comment]
> Excellent Work! The design appears to be a little off, but the functioning is perfect; I'll do the design modifications once I'm a little more free. Thank you so much for your contribution.

Thanks a lot @EshanTrivedi21 ❤☺

**Comment by EshanTrivedi21** [comment]
@pooranjoyb i have made the changes. Will be waiting for your valuable feedbacks.

**Comment by pooranjoyb** [comment]
> @pooranjoyb i have made the changes. Will be waiting for your valuable feedbacks.

Dayum it's really awesome & marvelous , nice work man! 💯

**Comment by EshanTrivedi21** [comment]
Thanks for the feedback, hoping to work with you again!

**Pull request merged**
