### PR TITLE
index-clean-up

### PR DESCRIPTION
**Pull request by samc18**
**ISSUE:** Index clean up #43

hi @EshanTrivedi21, I'm creating this PR to submit the latest version of the index.html with more accurate content.

### CODE REVIEW

**Review by EshanTrivedi21 — COMMENTED** [review]
The functionality isn't changing right?

**Comment by samc18** [comment]
No, is just some typos and some p elements didn't have a strong tag. The changes are looking a bit weird, I got stuck git the git CLI so I decided to start over, sorry for that!

**Comment by EshanTrivedi21** [comment]
Okay okay should I approve them if everything is fine from your side?

**Comment by samc18** [comment]
Yes, everything is good from my side, I made sure I only updated the things that were needed.

**Review by EshanTrivedi21 — APPROVED** [review]

**Pull request merged**
