### PR TITLE
change to neumorphism theme

### PR DESCRIPTION
**Pull request by super-duper-sp**
I have  change theme to neumorphism theme.

### CODE REVIEW

**Review by EshanTrivedi21 — CHANGES_REQUESTED** [review]
The changes are not up to the mark, 
image
this should have been the expected behavior of the website, can you please make the changes and update the pull request plz? Thanks for the efforts though, much appreciated!

**Comment by super-duper-sp** [comment]
Please,Review the changes.

**Comment by EshanTrivedi21** [comment]
@KCmean plz look into the matter and review the changes as per your needs

**Comment by super-duper-sp** [comment]
> Can you plz add a photo which i can refer to? @super-duper-sp

Screenshot 2022-10-18 at 11 32 25 PM

**Pull request closed without merging**
